#!/usr/bin/env bash
# assemble.sh — Containerfile assembler (SG8/SG9).
# Concatenates the enabled `.layer` modules of an image into a generated,
# committed Containerfile. Module inclusion is driven by toggles in the merged
# config (config.yaml + flavor chain). Runs anywhere (pure text); no host mutation.
#
# Module format (images/<image>/modules/NN-name.layer):
#   # module:  <short-name>                 (informational)
#   # toggle:  always | <yq.path.to.bool>   (REQUIRED — `always` or a config path)
#   # summary: <one line>                    (informational)
#   <Containerfile fragment lines...>
#
# Modules are included in lexical filename order (use NN- numeric prefixes).
# A module whose `toggle` is a config path is included only when that path is
# true in the merged config; `always` is unconditional.
#
# Usage:  assemble.sh <image-name> [--check]
#   writes images/<image-name>/Containerfile (or, with --check, exits 1 if the
#   on-disk Containerfile differs from what would be generated — for CI/commit gates).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
# shellcheck source=/dev/null
. "$SCRIPT_DIR/config.sh"

image="${1:?usage: assemble.sh <image-name> [--check]}"
mode="${2:-write}"
moddir="$ROOT/images/$image/modules"
out="$ROOT/images/$image/Containerfile"
[ -d "$moddir" ] || { echo "assemble: no modules dir at $moddir" >&2; exit 1; }

merged="$(merge_config "$ROOT")"

# Read a `# key:` value from a module's header comment block.
layer_meta() { sed -n "s/^#[[:space:]]*$2:[[:space:]]*//p" "$1" | head -1; }

gen="$(
  printf '# GENERATED by setup/lib/assemble.sh — DO NOT EDIT BY HAND.\n'
  printf '# Edit images/%s/modules/*.layer and re-run: setup/lib/assemble.sh %s\n' "$image" "$image"
  printf '# Enabled modules are chosen from config.yaml toggles (merged with the active flavor).\n'
  included=0
  shopt -s nullglob
  for m in "$moddir"/*.layer; do
    toggle="$(layer_meta "$m" toggle)"
    [ -n "$toggle" ] || { echo "assemble: $m missing '# toggle:' header" >&2; exit 1; }
    if [ "$toggle" != always ]; then
      val="$(cfg_get "$merged" ".$toggle" "false")"
      [ "$val" = true ] || continue
    fi
    included=$((included+1))
    printf '\n# --- module: %s  (toggle: %s) ---\n' "$(basename "$m")" "$toggle"
    # Strip the metadata header (module/toggle/summary/requires) — but ONLY within the leading
    # comment block, so a RUN-body line that happens to start with those keywords survives.
    awk '
      BEGIN { body = 0 }
      body == 0 && /^[[:space:]]*#[[:space:]]*(module|toggle|summary|requires):/ { next }
      /^[[:space:]]*#/ { print; next }
      { body = 1; print }
    ' "$m"
  done
  [ "$included" -gt 0 ] || { echo "assemble: no modules enabled for image '$image'" >&2; exit 1; }
)"

if [ "$mode" = --check ]; then
  if [ -f "$out" ] && diff -q <(printf '%s\n' "$gen") "$out" >/dev/null; then
    echo "[assemble] $image: Containerfile up to date."
  else
    echo "[assemble] $image: Containerfile OUT OF DATE — re-run assemble.sh $image" >&2
    exit 1
  fi
else
  printf '%s\n' "$gen" > "$out"
  echo "[assemble] wrote $out"
fi
