#!/usr/bin/env bash
# bootstrap.sh — probe the machine, match a flavor, generate+validate config (SG10).
# Idempotent: never clobbers an existing config.yaml or flavor (reports + validates them
# instead). On a fresh machine it scaffolds a config.yaml from facts and points you at the
# nearest flavor (or drafts one with uncertain fields flagged). Runs ON THE HOST.
# Hardware-specific values are NEVER written into config.yaml (they belong in a flavor).
# Usage:  bootstrap.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
# shellcheck source=/dev/null
. "$SCRIPT_DIR/config.sh"

FACTS="$ROOT/setup/facts.env"
CFG="$ROOT/config.yaml"

echo "== bootstrap: probing host =="
bash "$SCRIPT_DIR/detect.sh" --write "$FACTS" >/dev/null
# shellcheck source=/dev/null
. "$FACTS"
echo "  OS:   ${OS_ID} ${OS_VERSION} (${OS_VARIANT:-}, atomic=${ATOMIC})"
echo "  GPU:  ${GPU_VENDOR} ${GPU_GFX} (${GPU_CODENAME:-?}, pciid ${GPU_PCIID})"
echo "  CPU:  ${CPU_CORES} cores, ${RAM_GIB} GiB RAM"

# --- match a hardware flavor from detected facts ----------------------------
suggest_flavor=""
case "${GPU_CODENAME:-}" in
  strix-halo) suggest_flavor="${OS_ID}-${OS_VARIANT}-strix-halo" ;;
  "") : ;;
  *) suggest_flavor="${OS_ID}-${OS_VARIANT}-${GPU_CODENAME}" ;;
esac
os_flavor="${OS_ID}-${OS_VARIANT}"

echo "== bootstrap: flavor match =="
if [ -n "$suggest_flavor" ] && [ -f "$ROOT/flavors/$suggest_flavor.yaml" ]; then
  echo "  ✓ hardware flavor exists: flavors/$suggest_flavor.yaml"
elif [ -n "$suggest_flavor" ]; then
  echo "  ! no flavors/$suggest_flavor.yaml — DRAFT one extending '$os_flavor':"
  echo "      gpu.vendor=${GPU_VENDOR}  gpu.gfx=${GPU_GFX}  (CONFIRM: HSA override, llm_image, model, VRAM)"
  echo "      uncertain fields must be confirmed by a spike before use (do not guess)."
else
  echo "  ! GPU not recognized (${GPU_VENDOR}) — author a hardware flavor by hand using setup/schema/MANIFEST.md"
fi
[ -f "$ROOT/flavors/$os_flavor.yaml" ] && echo "  ✓ OS flavor exists: flavors/$os_flavor.yaml" \
  || echo "  ! no OS flavor flavors/$os_flavor.yaml — author from MANIFEST.md (pkg_manager/selinux/immutable)"

# --- config.yaml: validate if present, scaffold if absent -------------------
echo "== bootstrap: config.yaml =="
if [ -f "$CFG" ]; then
  echo "  config.yaml exists — validating (not overwriting)."
  bash "$SCRIPT_DIR/validate.sh" "$ROOT"
else
  if [ -z "$suggest_flavor" ]; then
    echo "  ✗ cannot scaffold config.yaml without a flavor name; author the flavor first." >&2
    exit 1
  fi
  echo "  scaffolding config.yaml (general layer only — no hardware values)."
  cat > "$CFG" <<YAML
# uumami_os — general configuration (generated by bootstrap; review before use).
flavor: $suggest_flavor

paths:
  containers: ~/Containers
  profiles:   ~/Profiles
  models:     ~/Models
  code:       ~/Code

container_engine: podman

llm:
  backend: ollama
  host: 127.0.0.1
  port: 11434

agents:
  claude_code: true
  codex: true
  opencode: true
  pi: true
  omp: true
  hermes: true
ide:
  cursor: true

tenants:
  default_tier: "2a"
  browser_default: shared
YAML
  echo "  wrote $CFG — now ensure flavors/$suggest_flavor.yaml exists, then re-run to validate."
fi
echo "== bootstrap done =="
